export enum LobbyEvent {
  PLAYER_ADDED = "LOBBY:PLAYER_ADDED",
  PLAYER_REMOVED = "LOBBY:PLAYER_REMOVED",
}

export enum MatchEvent {
  MATCHED = "SERVER:MATCH:MATCHED",
  READY = "SERVER:MATCH:READY",
  START = "SERVER:MATCH:"
}
